name: zkevm-chain
on:
  workflow_dispatch:
  repository_dispatch:
    types: [zkevm-chain]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  main:
    timeout-minutes: 5
    env:
      GH_PAT: ${{ secrets.PAT_OPS_PSE_ORG }}
      IMAGE_ID: ami-0a60600ebca79fab3
      KEY_NAME: pinkie
      SUBNET_ID: subnet-005b28c6bd85faa5c
      SECURITY_GROUP_ID: sg-0ec6bb25610783aeb
      REPO: privacy-scaling-explorations/zkevm-chain
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false
    steps:
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::490752553772:role/GH-Actions-ap-south
          role-duration-seconds: 900
          aws-region: ap-south-1
      - uses: actions/checkout@v2
      - run: ./run.sh
